name: build

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: 3
  RUSTFLAGS: -D warnings

jobs:

  build:
    name: Build
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
        exclude:
          - rust: nightly
            os: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ${{ matrix.rust }} Rust
        run: rustup default ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --all-features

      # This checks examples and benchmarks, which are not covered above.
      - name: Check all targets
        if: matrix.rust == 'nightly'
        run: cargo check --all-targets

  msrv:
    name: Build MSRV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect MSRV
        run: echo MSRV=$(grep 'rust-version' Cargo.toml | cut -d '"' -f 2) >> "$GITHUB_ENV"

      - name: Install Rust  ${{ env.MSRV }}
        run: rustup default $MSRV

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Build documentation and check intra-doc links
        env:
          RUSTDOCFLAGS: --deny rustdoc::broken_intra_doc_links
        run: cargo doc --no-deps

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Clippy with default lints
        run: cargo clippy

      - name: Lint for left-over debug prints
        run: cargo clippy -- -D clippy::print_stdout -D clippy::print_stderr
