name: format

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Formatting
        uses: dprint/check@v2.3
